export enum Path {
    organization= "/org",
    root = "/",
    futureLectures = "/futureLectures",
    followUp = "/followup",
    expectedIncome = "/expectedIncome",
    waitingPayment = "/payment",
    allOrders = "/allOrders",
    allPublicCourses = "/allPublicCourses",
    order = "/order",
    publicCourse = "/publicCourse",
    actionRequired = "/actionRequired",
    print = "/print",
    bi = "/bi",
}