export const SELECT_PUBLIC_COURSE = "SELECT_PUBLIC_COURSE";
export const UPDATE_SELECTED_PUBLIC_COURSE = "UPDATE_SELECTED_PUBLIC_COURSE";
export const SET_IS_SELECTED_PUBLIC_COURSE = "SET_IS_SELECTED_PUBLIC_COURSE";
export const CLEAR_SELECTED_PUBLIC_COURSE = "CLEAR_SELECTED_PUBLIC_COURSE";