language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "client/node_modules"
before_script:
- npm run client-install
script:
- npm run client-build
- npm run test
- npm run lint
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "development"