language: node_js
cache: bundler
node_js:
  - "node"
before_script:
- cd app
- npm install
script:
- npm run build
- npm run test
- npm run lint
after_success:
  - firebase deploy --token $FIREBASE_TOKEN -P dev --only hosting