language: node_js
node_js:
  - "node"
before_script:
- npm install --prefix client
script:
- npm test
- npm run lint
- npm run build
after_success:
- firebase deploy --token $FIREBASE_TOKEN -P development --only hosting
