language: node_js
cache: bundler
node_js:
  - "node"
install:
- npm run client-install
script:
- npm run client-build
- npm run test
- npm run lint
after_success:
- firebase deploy --token $FIREBASE_TOKEN -P development --only hosting
