language: node_js
cache: bundler
node_js:
  - "node"
before_script:
- npm run client-install
script:
- npm run client-build
- npm run test
- npm run lint
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "development"