export const SELECT_ORGANIZATION = "SELECT_ORGANIZATION";
export const SET_IS_SELECTED_ORGANIZATION = "SET_IS_SELECTED_ORGANIZATION";
export const SELECT_ORDER = "SELECT_ORDER";
export const CLEAR_SELECTED = "CLEAR_SELECTED";
export const CLEAR_SELECTED_ORDER = "CLEAR_SELECTED_ORDER";

