export const publicCourseLabels = {
    pageTitle: 'קורס ציבורי',
    sections: {
        courseDetailsSectionName: 'פרטי הקורס',
        courseLecturesSectionName: 'הרצאות',
        courseLectureDetailsSectionName: 'פרטי ההרצאות',
        courseParticipantsSectionName: 'משתתפים',
    },
    actionButtons: {
        save: 'שמור קורס',
        savedSuccessfully: 'קורס ציבורי {0} נשמר בהצלחה',
        sendingToDatabaseFailedTitle: 'שגיאה בשמירת קורס ציבוי',
        sendingToDatabaseFailedContent: 'חלה שגיאה בשמירת הקורס הציבוי בשרת',
        addLecture: 'הוסף הרצאה',
    },
    fieldTitles: {
        // Course Details
        courseName: 'שם הקורס',
        courseCity: 'עיר',
        courseLocation: 'מיקום הקורס',
        mealCost: 'עלות ארוחה',
        distanceCost: 'עלות נסיעות',
        roomsApproved: 'חדרים אושרו',
        isoPayed: 'שולם לאיגוד',
        printedMaterials: 'חוברות הודפסו',
        printedCertificates: 'תעודות הודפסו',

        // Lectures
        date: 'תאריך',
        startTime: 'שעת התחלה',
        endTime: 'שעת סיום',
        duration: 'משך',
        topic: 'נושא',
        tie: 'עניבה',
        price: 'מחיר ללקוח',
        roomCost: 'עלות החדר',
        pages: 'עמודים בחוברת',
        active: 'מתקיים',
        guestLecturer: 'מרצה אורח',
        guestLecturerName: 'שם מרצה אורח',
        guestLecturerCost: 'עלות מרצה אורח',
    },
    participantsTableHeaders: [
        {orderId: 'מספר הזמנה'},
        {participantFirstName: 'שם פרטי'},
        {participantLastName: 'שם משפחה'},
        {organizationName: 'ארגון'},
        {status: 'סטאטוס'},
        {proformaInvoiceNumber: 'חשבונית עסקה'},
        {numberOfLecturesAttending: 'ימים'},
        {participantCost: 'מחיר השתתפות'},
    ],
    LectureDetailsTableHeaders: [
        {date: 'תאריך'},
        {topic: 'נושא'},
        {participantsCount: 'מספר משתתפים'},
        {price: 'מחיר ללקוח'},
        {income: 'הכנסות'},
    ]
};