export const SELECT_ORGANIZATION = "SELECT_ORGANIZATION";
export const UPDATE_SELECTED_ORGANIZATION = "UPDATE_SELECTED_ORGANIZATION";
export const SET_IS_SELECTED_ORGANIZATION = "SET_IS_SELECTED_ORGANIZATION";
export const CLEAR_SELECTED_ORGANIZATION = "CLEAR_SELECTED_ORGANIZATION";