export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SHOW_REQUIRED_FIELDS = 'SHOW_REQUIRED_FIELDS';
export const HIDE_REQUIRED_FIELDS = 'HIDE_REQUIRED_FIELDS';