export const SELECT_ORDER = 'SELECT_ORDER';
export const UPDATE_SELECTED_ORDER = 'UPDATE_SELECTED_ORDER';
export const SET_IS_SELECTED_ORDER = 'SET_IS_SELECTED_ORDER';
export const CLEAR_SELECTED_ORDER = 'CLEAR_SELECTED_ORDER';